### ISSUE TITLE
An opiton menu for canceling altert

### ISSUE THREAD

**Issue by potpot3** [simov/screenshot-capture#15]
Great tool ，very easy to use，thank you very much！

Could you offer an opiton menu for canceling alert. Such alert is annoying.

alerts for example：

    //    'Screenshot Capture:',
    //    'Binary Image',
     //   'Saved to Clipboard!'

     //   'Screenshot Capture:',
     //   'Data URL String',
      //  'Saved to Clipboard!'

**Comment by simov** [comment]
Implemented in v3.1, more details here https://github.com/simov/screenshot-capture/issues/12#issuecomment-1820928850
