### ISSUE TITLE
Thank you 💌

### ISSUE THREAD

**Issue by p2edwards** [simov/screenshot-capture#21]
# Thank you for making this extension

Thanks for creating a simple, reliable screenshot utility, and making it easy to find.

Since most of the screenshots I take are rectangular regions of webpage, I was able to quickly install your extension, figure it out, and get back to work, after an update broke all of the available screenshot utilities on my chosen OS.

### Related
- #5

**Comment by blakkd** [comment]
@simov I add my thanks to those from p2edwards!
I really missed this feature in Firefox!

And 10 years of maintenance is something! Thanks for your commitment 🤟
