### ISSUE TITLE
Any chance to work on local files ?

### ISSUE THREAD

**Issue by ugurkanates** [simov/screenshot-capture#6]
I work on lots of PDFs and HTMLs that are stored locally , since this extension is awesome I wonder if anyone can enable it for local files as well 
( currently clicking button on local files on browser wont do the trick)

**Comment by simov** [comment]
The extension works for local files, you just have to enable it. Go to chrome://extensions, find Screenshot Capture, and click on Details, then find the switch that says: `Enable for Local File URLs`, and turn it on. You need to refresh the page after that.

**Comment by ugurkanates** [comment]
Lovely !
