### ISSUE TITLE
Unchecked runtime.lastError while running tabs.insertCSS: Cannot access a chrome:// URL

### ISSUE THREAD

**Issue by jetBn** [simov/screenshot-capture#9]
when i run is show this error

**Comment by simov** [comment]
Hi, the extension cannot work on certain [origins](https://github.com/simov/screenshot-capture#origins).

**Comment by jetBn** [comment]
can‘t  work about this extension?

**Comment by simov** [comment]
It is a limitation of Chrome. It doesn't allow extension on those URLs by default. You can enable it by navigating to this URL in Chrome chrome://flags/#extensions-on-chrome-urls
